import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import UserActionBtn from "@/components/layout/user-action-btn";
import Footer from "@/components/layout/footer";
import { Providers } from "./provider";
import Alert from "@/components/ui/alert";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <div className="flex w-screen h-screen">
            <Sidebar />
            <div id="main" className="relative w-full overflow-y-auto p-8 z-0">
              <Alert />
              <div id="notifications"></div>
              {children}
            </div>
            <UserActionBtn />
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
