import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/sidebar";
import UserActionBtn from "@/components/layout/user-action-btn";
import Footer from "@/components/layout/footer";
import { Providers } from "./provider";
import { Provider } from "react-redux";
import store from "@/store/index";
import { Schedule } from "@/util/interfaces";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { allSchedules } = await getAllSchedulesData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex w-screen h-screen">
            <Sidebar allSchedules={allSchedules} />
            <>
              <div
                id="main"
                className="relative w-full overflow-y-auto p-8 z-0"
              >
                {children}
              </div>
            </>
            <UserActionBtn />
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}

export async function getAllSchedulesData() {
  try {
    const response = await fetch("http://localhost:3000/api/schedules");

    if (!response.ok) {
      throw Error("스케줄 불러오는데 실패했습니다.");
    }
    const allSchedules: Schedule[] = await response.json();

    return { allSchedules };
  } catch (err: any) {
    throw Error("스케줄 불러오는데 실패했습니다.", err);
  }
}
